### PR TITLE
Add support for passing function source

### PR DESCRIPTION
**Pull request by matthewwardrop**
Greetings again pgiri,

Sorry about the shuffle. I realised a pull request from my master branch was a bad idea as it meant I could not easily update the pull request with respect to your changes. And then I had to learn how to properly use rebase. Below is the original message (edited to reflect current status of master), along with your reply:

I spoke once before with you about adding support for providing to Dispy the source code of python functions rather than the functions themselves. I'm not sure if I made the use case for this clear, but it is necessary in my use case.

The main use case is as follows: Suppose you have some complex class with many runtime variable properties, none of which will be accessible when the setup/cleanup/computation functions are run in the new environment of dispynode; and yet you need access to these properties to properly reconstruct your object. One solution, as I have implemented it, is to send the source code, rather than the Python function. The source code can then be "formatted" with the values of the properties you need. Sending an 'exec'ed version will not work, because inspect.getsourcelines requires that the python function be associated with a filename on the hard drive.

Any thoughts on this? If you're not keen to include it, I'm okay with that. But if there are things you want addressed with my patch, let me know, and I'll improve it :).

--------

I will go through it again; it seems fairly extensive.

I am not sure if I am missing something, but I believe you can send classes in 'depends' parameter. Then even 'setup' will be able to use objects (class instances). Can you give an example that needs this patch?

### CODE REVIEW

**Comment by matthewwardrop** [comment]
Okay, here is a minimal example where being able to send the source for functions to be remotely operated could be very useful; and in my case necessary.

Suppose you have some class:
```
class Greeter(object):

	def __init__(self, greeting='Hello'):
		self.greeting = greeting
	
	def greet(self, name="Matthew"):
		print "%s %s" % ( self.greeting, name)
```
And your `compute` function requires an instance of `Greeter` to be in the global namespace when it runs. Okay. Simple, right? You add `Greeter` to depends, either by its module or by its classname. Then, you write for setup the function:
```
def setup():
	global greeter
	greeter = Greeter('Bonjour')
```
But what happens if you want the greeting to depend on runtime values of the host running `JobCluster`? For example:

```
class BigComplexClass(object):
	greeting = "Hiya"
	
	def run_jobserver(self):
		setup = '''
		def setup():
			global greeter
			greeter = Greeter('%s')
		''' % self.greeting
		JobCluster(.....,setup=setup)
```

It is a little heavy-handed to reconstruct the entire logic of the job server, when all you need is a simply parameter value. Since the setup function cannot depend on variables in the global state, you could pipe the values out to a python source file, and then pass add that file to the `depends` list... but that is a very roundabout way of getting the source. The easiest way is simply to create the source in memory, and pass that to `JobCluster`... well, if it supported it. The pull request adds this support.

Is there something I'm missing?

**Comment by matthewwardrop** [comment]
I'm happy to make any changes you deem necessary to get this pulled, btw.

**Comment by pgiri** [comment]
Unless I am mistaken, 'depends' can be used to pass given Greeter class, a function to initialize the class (what is done in the string in your example) - note that depends is a list of classes, functions, files, objects. All of these will be available on the node before 'setup' function is executed. Moreover, any object initialization can be done on the client and simply included in the 'depends'; dispy will send it along.

If this is not sufficient, please give a full example (it doesn't have to be meaningful - it can be as simple as possible). If that example can't be encoded with 'depends' as it is now, let us think about it.

**Comment by matthewwardrop** [comment]
Did you try running the above code? The problem was never in sending `Greeter` (or rather, not only in sending `Greeter`; see my other pull request: https://github.com/pgiri/dispy/pull/11). The problem is that it is not possible to initialise `Greeter` with variables local to classes not running on the server. This is useful for example when constructing the setup/compute/cleanup functions depending on the current state of client code (for example, variables read in from the command line or other runtime variables, as demonstrate in the above code). To make things easier for you, here is a complete example demonstrating the problem with the current setup.

```
class Greeter(object):

    def __init__(self, greeting='Hello'):
        self.greeting = greeting

    def greet(self, name="Matthew"):
        print "%s %s" % ( self.greeting, name)

def compute(name):
    greeter.greet(name)

def callback(job):
    print job.stdout

def setup_simple():
    global greeter
    greeter = Greeter("HI")
    return 0

from dispy import JobCluster

class BigComplexClass(object):
    greeting = "Hiya"
    names = ['Matthew', 'Mark', 'Luke', 'John']

    def run_jobserver(self):

        def setup_using_locals():
            global greeter
            greeter = Greeter(self.greeting)
            return 0

        setup_that_works = '''
        def setup():
            global greeter
            greeter = Greeter('%s')
            return 0
        ''' % self.greeting

        cluster = JobCluster(compute,
            #setup=setup_simple, # This will work (once my other patch is pulled)
            #setup=setup_using_locals, # This will NOT work because it attempts to use `self` which is not available on the server
            #setup=setup_that_works, # This will work with *this* patch
            depends=[Greeter],
            cleanup=False,
            callback=callback)

        for name in self.names:
            cluster.submit(name)

        cluster.wait()
        cluster.stats()
        cluster.close()

if __name__ == "__main__":
    bcc = BigComplexClass()
    bcc.run_jobserver()

```

**Comment by matthewwardrop** [comment]
Did you make any headway into this? Am I still missing something?

**Comment by matthewwardrop** [comment]
Ah... Sorry. I reread your response earlier and I can see what you mean about creating the object on the client and then just sending it on. There are two reasons, I think, why this is insufficient:
1) constructing the object maybe costly, and so you only want to do it once per node, and never on the client
2) the  class instance is not pickleable, due to its having attributes that are functions, etc.

As it happens, both are true in my application. If you need a simple example of (2), let me know.

**Comment by matthewwardrop** [comment]
Okay; so I withdraw my previous commit. Currently there is no way to pass a prepopulated object from the host to the server. If you pass such an object in `depends`, then it just maps it to the class of which it is an instance, and sends that code.

Allowing clients to provide source code is one solution, but I agree it is not necessarily clean. I will code up an alternative approach that allows you to inject pickleable objects into the namespace of the running code, making this pull request obsolete.

I will leave it open in case you disagree, and think this is a better approach.

**Pull request closed without merging**
