### PR TITLE
Adding the case when node_port is 0. Argument -p 0

### PR DESCRIPTION
**Pull request by lcasassa**
dispaynode.py -p 0 should choose any available port.

### CODE REVIEW

**Comment by pgiri** [comment]
I am wondering how useful this feature is: It may work for one node, so one can note that port number and then create cluster to use that node. However, using more than one node is not easy (it is possible to create different NodeAllocate or tuples in 'nodes'), as different instances use different ports. Is there more work pending to use this feature in clients?

The patch itself doesn't break existing features, so it is harmless, but documenting this feature is again not simple!

**Comment by lcasassa** [comment]
We are using subprocess to launch a command on a remote computer with dispy. That subprocess uses more than one cpu defined on a ui by the user so one slot per cpu will not do in this case. In this ui the user can launch nodes on local and remote computers using spur (ssh). This just avoids an unnecessary error when a node uses a port that is already in use by someone else when selecting port 0. It can be used by another node but also by another process that has nothing to do with dispay. So we are just avoiding an error. On our ui, the user can easily see that it has two or more nodes on the same computer and the amount of cpus and slots for each so he would know what is going on.

I would like to thank you for dispy, we are using it and loving it!

**Comment by pgiri** [comment]
Thanks for your patch. I merged it and also committed similar patch for py3 branch.

**Comment by lcasassa** [comment]
Thanks!!

**Pull request merged**
